apiVersion: eksctl.io/v1alpha5
kind: ClusterConfig

metadata:
  name: observability
  region: us-east-1

vpc:
  subnets:
    private:
      us-east-1a: {}
      us-east-1b: {}
    public:
      us-east-1a: {}
      us-east-1b: {}

nodeGroups:
  - name: observability-ng-private
    instanceType: t3.medium
    desiredCapacity: 2
    minSize: 2
    maxSize: 3
    volumeSize: 20
    privateNetworking: true
    managed: true
    iam:
      withAddonPolicies:
        autoScaler: true
        externalDNS: true
        ecrFullAccess: true
        appMesh: true
        albIngress: true
