apiVersion: v1
kind: Pod
metadata:
  labels:
    run: mem-demo-2
  name: mem-demo-2
  namespace: memory-ns
spec:
  containers:
  - image: polinux/stress
    name: mem-demo-2
    resources: 
      requests:
        memory: "50Mi"
        cpu: "100m"
      limits:
        memory: "100Mi"
        cpu: "150m"
    command: ["stress"]
    args: ["--vm", "1", "--vm-bytes", "250M", "--vm-hang", "1"]
