apiVersion: v1
kind: Pod
metadata:
  labels:
    run: mem-demo
  name: mem-demo
  namespace: memory-ns
spec:
  containers:
  - image: polinux/stress
    name: mem-demo
    resources: 
      requests:
        memory: "100Mi"
      limits:
        memory: "200Mi"
    command: ["stress"]
    args: ["--vm", "1", "--vm-bytes", "150M", "--vm-hang", "1"]
  dnsPolicy: ClusterFirst
  restartPolicy: Always
status: {}
