apiVersion: v1
kind: Pod
metadata:
  labels:
    run: nginx-2
  name: nginx-2
spec:
  containers:
  - image: nginx:latest
    name: nginx-2
  affinity:
    podAntiAffinity:
      requiredDuringSchedulingIgnoredDuringExecution:
        - labelSelector:
            matchExpressions:
              - key: "app"
                operator: "In"
                values:
                  - "backend"
          topologyKey: "kubernetes.io/hostname"