apiVersion: v1
kind: Pod
metadata:
  name: redis-pod
  labels:
    role: db
spec:
  containers:
  - name: redis-container
    image: redis:latest
    resources:
      limits:
        memory: "128Mi"
        cpu: "500m"
    ports:
    - containerPort: 6379
    volumeMounts:
    - name: redis-storage
      mountPath: "/data/redis"
  volumes:
  - name: redis-storage
    emptyDir: {}
