apiVersion: v1
kind: Pod
metadata:
  labels:
    run: configmap-demo-pod
  name: configmap-demo-pod
spec:
  containers:
  - image: busybox:1.28
    name: configmap-demo-container
    command: ["sh", "-c", "sleep 36000"]
    env:
    - name: FIRSTNAME
      valueFrom:
        configMapKeyRef:
          name: app-cm
          key: firstname
    - name: LASTNAME
      valueFrom:
        configMapKeyRef:
          name: app-cm
          key: lastname
  dnsPolicy: ClusterFirst
  restartPolicy: Always
status: {}
