apiVersion: v1
kind: Pod
metadata:
  labels:
    run: redis
  name: redis
  namespace: default
spec:
  containers:
  - image: redis:latest
    imagePullPolicy: Always
    name: redis
  tolerations:
    - key: "gpu"
      operator: "Equal"
      value: "true"
      effect: "NoSchedule"