apiVersion: v1
kind: Pod
metadata:
  name: redis-pod
  labels:
    name: redis-pod
spec:
  containers:
  - name: redis-pod
    image: redis:latest
    resources:
      limits:
        memory: "128Mi"
        cpu: "500m"
    ports:
      - containerPort: 6379
    volumeMounts:
    - name: local-volume
      mountPath: "/data/redis" 
  volumes:
  - name: local-volume
    persistentVolumeClaim:
      claimName: my-local-pvc
